# .vale.ini
StylesPath = styles
MinAlertLevel = suggestion

# Archivos a analizar
[*.{md,txt,json,yml,yaml}]
BasedOnStyles = Microsoft, Custom

# Ignorar carpetas innecesarias
[*.{md,txt,json,yml,yaml}]
IgnoredScopes = code, pre, script
