version: "0.3"
matrix:
  - name: Markdown
    sources:
      - "**/*.md"
    dictionary:
      language: en_US
    aspell:
      lang: en
      add-extra-dicts: true

  - name: JSON
    sources:
      - "**/*.json"
    dictionary:
      language: en_US
    aspell:
      lang: en
      add-extra-dicts: true

allow:
  - GitHub
  - API
  - JSON
  - Markdown
  - README
