version: "0.3"
matrix:
  - name: Markdown
    sources:
      - "**/*.md"
    dictionary:
      language: en_US
    hunspell:
      dictionaries:
        - en_US

  - name: JSON
    sources:
      - "**/*.json"
    dictionary:
      language: en_US
    hunspell:
      dictionaries:
        - en_US

allow:
  - GitHub
  - API
  - JSON
  - Markdown
  - README
