<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Services\Configurations\**" />
    <EmbeddedResource Remove="Services\Configurations\**" />
    <None Remove="Services\Configurations\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UcarMobileApi.Core\UcarMobileApi.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="AutoMapper.Collection.EntityFrameworkCore" Version="11.0.0" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="GeoTimeZone" Version="6.1.0" />
    <PackageReference Include="Gridify.EntityFramework" Version="2.16.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="PublicHoliday" Version="3.9.0" />
    <PackageReference Include="Stripe.net" Version="49.0.0" />
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
  </ItemGroup>
</Project>
