using AutoMapper;
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using UcarMobileApi.Application.DTOs.Users;
using UcarMobileApi.Application.Services.Auth;
using UcarMobileApi.Application.Services.Security;
using UcarMobileApi.Core.Entities.Users;
using UcarMobileApi.Infrastructure.Data;

public class AuthService(
    AppDbContext context,
    IUserAuthorizationService authorizationService,
    IConfiguration configuration,
    IValidator<CreateUserDto> validator,
    IMapper mapper) : IAuthService
{
    public async Task<UserDto> RegisterUserAsync(CreateUserDto request, CancellationToken cancellationToken = default)
    {
        // 🔹 Validate input using FluentValidation
        var validationResult = await validator.ValidateAsync(request, cancellationToken);
        if (!validationResult.IsValid)
            throw new ValidationException(validationResult.Errors);

        // 🔹 Check if user already exists (fast check with AnyAsync)
        var exists = await context.Set<User>()
            .AsNoTracking()
            .AnyAsync(u => u.CognitoId == request.CognitoId || u.Email == request.Email, cancellationToken);

        if (exists)
            throw new InvalidOperationException("User already exists.");

        // 🔹 Map DTO to entity (Id will be generated by the database)
        var user = mapper.Map<User>(request);
        user.IsActive = true;

        // 🔹 Load default role id (Customer) 
        var customerRoleId = await context.Set<Role>()
            .Where(r => r.Name == "Customer")
            .Select(r => r.Id)
            .FirstOrDefaultAsync(cancellationToken);

        if (customerRoleId == default)
            throw new InvalidOperationException("Default role 'Customer' not found.");

        // 🔹 Associate role via navigation property (no need for UserId yet)
        user.UserRoles.Add(new UserRole
        {
            RoleId = customerRoleId,
        });

        // 🔹 Save User and UserRole in a single transaction
        await context.Set<User>().AddAsync(user, cancellationToken);
        await context.SaveChangesAsync(cancellationToken);

        // 🔹 Project user directly to UserDto (optimized SELECT with joins)
        var createdUserDto = await context.Set<User>()
            .AsNoTracking()
            .Where(u => u.Id == user.Id)
            .Select(u => new UserDto
            {
                Id = u.Id,
                CognitoId = u.CognitoId,
                FirstName = u.FirstName,
                LastName = u.LastName,
                Email = u.Email,
                IsActive = u.IsActive,
                Roles = u.UserRoles.Select(ur => new RoleDto
                {
                    Id = ur.Role.Id,
                    Name = ur.Role.Name,
                    Description = ur.Role.Description,
                    Permissions = ur.Role.RolePermissions.Select(ra => new PermissionDto
                    {
                        Id = ra.Permission.Id,
                        Name = ra.Permission.Name,
                        Description = ra.Permission.Description
                    }).ToList()
                }).ToList()
            })
            .FirstOrDefaultAsync(cancellationToken);

        if (createdUserDto == null)
            throw new InvalidOperationException("User creation failed.");

        return createdUserDto;
    }

    public async Task<object> GetCurrentUserAsync(string cognitoId, CancellationToken cancellationToken = default)
    {
        // 🔹 Project user and roles directly without tracking
        var userProjection = await context.Set<User>()
            .AsNoTracking()
            .Where(u => u.CognitoId == cognitoId)
            .Select(u => new
            {
                u.Id,
                u.CognitoId,
                u.FirstName,
                u.LastName,
                u.Email,
                u.IsActive,
                Roles = u.UserRoles.Select(ur => ur.Role.Name).ToList()
            })
            .FirstOrDefaultAsync(cancellationToken);

        if (userProjection == null)
            throw new KeyNotFoundException("User not found.");

        if (!userProjection.IsActive)
            throw new UnauthorizedAccessException("User is inactive.");

        // 🔹 Retrieve permissions using the authorization service
        var permissions = await authorizationService.GetUserPermissionsAsync(cognitoId);

        return new
        {
            userProjection.Id,
            userProjection.CognitoId,
            userProjection.FirstName,
            userProjection.LastName,
            userProjection.Email,
            userProjection.IsActive,
            userProjection.Roles,
            Permissions = permissions
        };
    }

    public async Task InitializeSystemAsync(CancellationToken cancellationToken = default)
    {
        var systemCognitoId = configuration["SystemUser:CognitoId"];
        if (string.IsNullOrWhiteSpace(systemCognitoId))
            throw new InvalidOperationException("SystemUser:CognitoId is not configured.");

        // 🔹 Use transaction to avoid race conditions during system initialization
        await using var tx = await context.Database.BeginTransactionAsync(cancellationToken);

        try
        {
            var existingSystemUser = await context.Set<User>()
                .AsNoTracking()
                .FirstOrDefaultAsync(u => u.CognitoId == systemCognitoId, cancellationToken);

            if (existingSystemUser != null)
                throw new InvalidOperationException("System has already been initialized.");

            // 🔹 Create system user (not saved yet)
            var systemUser = new User
            {
                CognitoId = systemCognitoId,
                FirstName = "System",
                LastName = "Administrator",
                Email = configuration["SystemUser:Email"] ?? "system@carrepair.com",
                IsActive = true
            };

            await context.Set<User>().AddAsync(systemUser, cancellationToken);

            // 🔹 Ensure basic roles exist
            var requiredRoles = new[]
            {
                ("Admin", "Full access to the system"),
                ("Technician", "Access to assigned jobs and technical reports"),
                ("Customer", "Access to schedule and manage own appointments")
            };

            // Load existing roles in one query
            var existingRoles = await context.Set<Role>()
                .Where(r => requiredRoles.Select(rr => rr.Item1).Contains(r.Name))
                .ToListAsync(cancellationToken);

            // Add missing roles
            foreach (var (name, description) in requiredRoles)
            {
                if (!existingRoles.Any(r => r.Name == name))
                {
                    var role = new Role
                    {
                        Name = name,
                        Description = description
                    };
                    await context.Set<Role>().AddAsync(role, cancellationToken);
                    existingRoles.Add(role); // keep in memory
                }
            }

            // 🔹 Save SystemUser + Roles in one batch
            await context.SaveChangesAsync(cancellationToken);

            // 🔹 Now existingRoles contain valid Ids
            var allPermissions = await context.Set<UcarMobileApi.Core.Entities.Users.Permission>()
                .AsNoTracking()
                .ToListAsync(cancellationToken);

            var roleNameToId = existingRoles.ToDictionary(r => r.Name, r => r.Id);

            // Load existing RolePermissions to avoid duplicates
            var roleIds = roleNameToId.Values.ToList();
            var existingRolePermissions = await context.Set<RolePermission>()
                .Where(ra => roleIds.Contains(ra.RoleId))
                .Select(ra => new { ra.RoleId, ra.PermissionId })
                .ToListAsync(cancellationToken);

            var toInsert = new List<RolePermission>();

            // 🔹 Assign actions to Admin (all)
            if (roleNameToId.TryGetValue("Admin", out var adminRoleId))
            {
                var missing = allPermissions
                    .Where(a => !existingRolePermissions.Any(era => era.RoleId == adminRoleId && era.PermissionId == a.Id))
                    .Select(a => new RolePermission { RoleId = adminRoleId, PermissionId = a.Id })
                    .ToList();
                toInsert.AddRange(missing);
            }

            // 🔹 Assign actions to Technician (subset)
            if (roleNameToId.TryGetValue("Technician", out var techRoleId))
            {
                var techPermissionNames = new[] { "appointment.view.own", "appointment.modify", "report.technician" };
                var missing = allPermissions
                    .Where(a => techPermissionNames.Contains(a.Name)
                                && !existingRolePermissions.Any(era => era.RoleId == techRoleId && era.PermissionId == a.Id))
                    .Select(a => new RolePermission { RoleId = techRoleId, PermissionId = a.Id })
                    .ToList();
                toInsert.AddRange(missing);
            }

            // 🔹 Assign actions to Customer (subset)
            if (roleNameToId.TryGetValue("Customer", out var customerRoleId))
            {
                var customerPermissionNames = new[] { "appointment.schedule", "appointment.modify", "appointment.cancel", "appointment.view.own" };
                var missing = allPermissions
                    .Where(a => customerPermissionNames.Contains(a.Name)
                                && !existingRolePermissions.Any(era => era.RoleId == customerRoleId && era.PermissionId == a.Id))
                    .Select(a => new RolePermission { RoleId = customerRoleId, PermissionId = a.Id })
                    .ToList();
                toInsert.AddRange(missing);
            }

            // 🔹 Insert new RolePermissions if any
            if (toInsert.Any())
                await context.Set<RolePermission>().AddRangeAsync(toInsert, cancellationToken);

            // 🔹 Save RolePermissions
            await context.SaveChangesAsync(cancellationToken);

            // Commit transaction
            await tx.CommitAsync(cancellationToken);
        }
        catch
        {
            await tx.RollbackAsync(cancellationToken);
            throw;
        }
    }
}
