name: Vale Linter

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.json'

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2
        with:
          styles: |
            Microsoft
          minAlertLevel: suggestion
